Fixes and install v12 from sources

diff --git a/12/Dockerfile b/12/Dockerfile
--- a/12/Dockerfile
+++ b/12/Dockerfile
@@ -1,9 +1,5 @@
-FROM odoo:12
-MAINTAINER IDAZCO
-USER root
+FROM debian:stretch
 
-# Generate locale C.UTF-8 for postgres and general locale data
-ENV LANG C.UTF-8
 
 ######
 # tini
@@ -13,24 +9,42 @@ ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
 RUN chmod +x /tini
 
 
-#####################
-# Deps & permissions
-#####################
-COPY download/addons/selected /mnt/extra-addons/
-RUN set -x; apt update && apt install -y \
- 	nginx \
-	&& rm -rf /var/lib/apt/lists/* /var/tmp/* \
-	&& chown odoo:root /etc/odoo
+# Generate locale C.UTF-8 for postgres and general locale data
+ENV LANG C.UTF-8
 
-
-##############
-# Deps config
-##############
-COPY nginx.conf /etc/nginx/nginx.conf
-COPY entrypoint.sh /
+# Install some deps, lessc and less-plugin-clean-css, and wkhtmltopdf
 RUN set -x; \
-	chown -R odoo:odoo /var/lib/nginx \
-	&& chown -R odoo:odoo /var/log/nginx
+        apt-get update \
+        && apt-get install -y --no-install-recommends \
+            ca-certificates \
+            curl \
+            dirmngr \
+            fonts-noto-cjk \
+            gnupg \
+            gcc \
+            libssl1.0-dev \
+            node-less \
+            python3-pip \
+            python3-dev \
+            python3-wheel \
+            python3-venv \
+            python3-pyldap \
+            python3-qrcode \
+            python3-renderpm \
+            python3-setuptools \
+            python3-vobject \
+            python3-watchdog \
+            build-essential \
+            xz-utils \
+            nginx \
+        && curl -o wkhtmltox.deb -sSL https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.stretch_amd64.deb \
+        && echo '7e35a63f9db14f93ec7feeb0fce76b30c08f2057 wkhtmltox.deb' | sha1sum -c - \
+        && dpkg --force-depends -i wkhtmltox.deb\
+        && apt-get -y install -f --no-install-recommends \
+        && rm -rf /var/lib/apt/lists/* wkhtmltox.deb  \
+		&& mkdir /opt/odoo \
+		&& adduser --disabled-password --gecos "" odoo \
+		&& chown -R odoo:odoo /opt/odoo
 
 
 #############
@@ -49,14 +63,51 @@ RUN DEBIAN_FRONTEND=noninteractive \
 	apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
 
+# Install rtlcss (on Debian stretch)
+RUN set -x;\
+    echo "deb http://deb.nodesource.com/node_8.x stretch main" > /etc/apt/sources.list.d/nodesource.list \
+    && export GNUPGHOME="$(mktemp -d)" \
+    && repokey='9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280' \
+    && gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "${repokey}" \
+    && gpg --armor --export "${repokey}" | apt-key add - \
+    && gpgconf --kill all \
+    && rm -rf "$GNUPGHOME" \
+    && apt-get update \
+    && apt-get install -y nodejs \
+    && npm install -g rtlcss \
+    && rm -rf /var/lib/apt/lists/*
+
+
+# Install Odoo (from source, this is another place we diverge)
+
+##################
+# Copy and config
+##################
+COPY download/odoo-12.0 /opt/odoo/
+COPY download/addons/selected /mnt/extra-addons/
+COPY nginx.conf /etc/nginx/nginx.conf
+COPY run-demo.conf /etc/odoo/odoo.conf
+COPY entrypoint.sh /
+COPY requirements.txt /tmp/requirements.txt
+RUN set -x; \
+	mkdir -p /var/lib/odoo && \
+	ln -s /opt/odoo/odoo-bin /usr/bin/odoo && \
+	chown -R odoo:root /etc/odoo && \
+	chown -R odoo:odoo /var/lib/odoo && \
+	chown -R odoo:odoo /var/lib/nginx && \
+    chown -R odoo:odoo /var/log/nginx && \
+	chmod +x /entrypoint.sh && \
+	pip3 install wheel && \
+	pip3 install -r /tmp/requirements.txt && \
+	pip3 install -r /opt/odoo/requirements.txt && \
+    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+
+
 ##########
 # Startup
 ##########
-# make sure the entry point file is executable
-RUN chmod +x /entrypoint.sh
-
 # the Docker healthcheck command
-#HEALTHCHECK CMD curl --fail http://127.0.0.1:8069/web_editor/static/src/xml/ace.xml || exit 1
+#HEALTHCHECK CMD curl --fail <todo> || exit 1
 
 # Expose proxy
 EXPOSE 8080
@@ -67,5 +118,7 @@ ENV ODOO_RC /etc/odoo/odoo.conf
 # Set default user when running the container
 USER odoo
 
+RUN export PYTHONIOENCODING=UTF-8
+
 ENTRYPOINT ["/tini", "--", "/entrypoint.sh"]
-CMD ["odoo"]
+CMD ["/opt/odoo/odoo-bin"]
